/**
 * Utility service for common operations and helpers
 */

// =====================================================
// COMMAND UTILITIES
// =====================================================

/**
 * Copy text to clipboard with feedback
 */
export const copyToClipboard = async (text: string, label: string = 'Copied'): Promise<boolean> => {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (err) {
    console.error('Failed to copy:', err);
    return false;
  }
};

/**
 * Download text as file
 */
export const downloadAsFile = (content: string, filename: string) => {
  const element = document.createElement('a');
  element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(content));
  element.setAttribute('download', filename);
  element.style.display = 'none';
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
};

/**
 * Export command as PowerShell script
 */
export const exportAsScript = (command: string, filename: string = 'command.ps1') => {
  const script = `# PowerShell Script Generated by Attack Payload System\n# Generated: ${new Date().toISOString()}\n\n${command}`;
  downloadAsFile(script, filename);
};

/**
 * Highlight placeholder syntax in command template
 */
export const highlightPlaceholders = (text: string): string => {
  return text.replace(/\{\{(\w+)\}\}/g, '<span class="text-orange-500 font-semibold">{{$1}}</span>');
};

/**
 * Extract placeholders from command template
 */
export const extractPlaceholders = (template: string): string[] => {
  const regex = /\{\{(\w+)\}\}/g;
  const placeholders: string[] = [];
  let match;

  while ((match = regex.exec(template)) !== null) {
    placeholders.push(match[1]);
  }

  return [...new Set(placeholders)]; // Remove duplicates
};

/**
 * Validate required fields
 */
export const validateFieldValues = (
  fields: Array<{ name: string; type: string; required: boolean }>,
  values: Record<string, string>
): { valid: boolean; errors: Record<string, string> } => {
  const errors: Record<string, string> = {};

  for (const field of fields) {
    if (field.required && (!values[field.name] || values[field.name].trim() === '')) {
      errors[field.name] = `${field.name} is required`;
    }

    if (values[field.name]) {
      const error = validateFieldType(field.type, values[field.name]);
      if (error) {
        errors[field.name] = error;
      }
    }
  }

  return {
    valid: Object.keys(errors).length === 0,
    errors,
  };
};

/**
 * Validate individual field based on type
 */
export const validateFieldType = (type: string, value: string): string | null => {
  if (!value) return null;

  switch (type) {
    case 'email':
      return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value) ? null : 'Invalid email format';

    case 'ip':
      return /^(\d{1,3}\.){3}\d{1,3}$|^([0-9a-f]{0,4}:){2,7}[0-9a-f]{0,4}$/i.test(value)
        ? null
        : 'Invalid IP address';

    case 'port':
      const port = parseInt(value, 10);
      return port >= 1 && port <= 65535 ? null : 'Port must be between 1 and 65535';

    case 'url':
      return /^https?:\/\/.+/i.test(value) ? null : 'Invalid URL (must start with http:// or https://)';

    case 'domain':
      return /^([a-z0-9](-[a-z0-9])*\.)+[a-z]{2,}$/i.test(value) ? null : 'Invalid domain format';

    case 'number':
      return /^-?\d+(\.\d+)?$/.test(value) ? null : 'Invalid number format';

    default:
      return null;
  }
};

// =====================================================
// FORMAT UTILITIES
// =====================================================

/**
 * Format bytes to human-readable size
 */
export const formatBytes = (bytes: number, decimals = 2): string => {
  if (bytes === 0) return '0 Bytes';

  const k = 1024;
  const dm = decimals < 0 ? 0 : decimals;
  const sizes = ['Bytes', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));

  return parseFloat((bytes / Math.pow(k, i)).toFixed(dm)) + ' ' + sizes[i];
};

/**
 * Format date to readable format
 */
export const formatDate = (dateString: string): string => {
  const date = new Date(dateString);
  return new Intl.DateTimeFormat('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  }).format(date);
};

/**
 * Format relative time (e.g., "2 hours ago")
 */
export const formatRelativeTime = (dateString: string): string => {
  const date = new Date(dateString);
  const now = new Date();
  const seconds = Math.floor((now.getTime() - date.getTime()) / 1000);

  const intervals = {
    year: 31536000,
    month: 2592000,
    week: 604800,
    day: 86400,
    hour: 3600,
    minute: 60,
  };

  for (const [key, value] of Object.entries(intervals)) {
    const interval = Math.floor(seconds / value);
    if (interval >= 1) {
      return `${interval} ${key}${interval > 1 ? 's' : ''} ago`;
    }
  }

  return 'just now';
};

/**
 * Truncate text with ellipsis
 */
export const truncateText = (text: string, maxLength: number): string => {
  return text.length > maxLength ? text.substring(0, maxLength) + '...' : text;
};

// =====================================================
// CATEGORY UTILITIES
// =====================================================

/**
 * Parse category string into major and subcategory
 */
export const parseCategory = (categoryString: string): { major: string; subcategory: string } | null => {
  const parts = categoryString.split(' - ');
  if (parts.length === 2) {
    return {
      major: parts[0],
      subcategory: parts[1],
    };
  }
  return null;
};

/**
 * Get major category from full category string
 */
export const getMajorCategory = (categoryString: string): string => {
  const parsed = parseCategory(categoryString);
  return parsed?.major || categoryString;
};

/**
 * Get subcategory from full category string
 */
export const getSubcategory = (categoryString: string): string => {
  const parsed = parseCategory(categoryString);
  return parsed?.subcategory || '';
};

// =====================================================
// ARRAY UTILITIES
// =====================================================

/**
 * Remove duplicates from array
 */
export const uniqueArray = <T,>(array: T[]): T[] => {
  return [...new Set(array)];
};

/**
 * Group array items by key
 */
export const groupBy = <T,>(array: T[], key: keyof T): Record<string, T[]> => {
  return array.reduce((groups, item) => {
    const groupKey = String(item[key]);
    if (!groups[groupKey]) {
      groups[groupKey] = [];
    }
    groups[groupKey].push(item);
    return groups;
  }, {} as Record<string, T[]>);
};

/**
 * Sort array by multiple criteria
 */
export const sortBy = <T,>(array: T[], criteria: (item: T) => any): T[] => {
  return [...array].sort((a, b) => {
    const aVal = criteria(a);
    const bVal = criteria(b);
    return aVal > bVal ? 1 : -1;
  });
};

// =====================================================
// URL UTILITIES
// =====================================================

/**
 * Build query string from object
 */
export const buildQueryString = (params: Record<string, any>): string => {
  const filtered = Object.entries(params)
    .filter(([_, value]) => value !== undefined && value !== null && value !== '')
    .map(([key, value]) => `${encodeURIComponent(key)}=${encodeURIComponent(value)}`)
    .join('&');

  return filtered ? '?' + filtered : '';
};

/**
 * Parse query string to object
 */
export const parseQueryString = (queryString: string): Record<string, string> => {
  const params = new URLSearchParams(queryString);
  const result: Record<string, string> = {};

  params.forEach((value, key) => {
    result[key] = value;
  });

  return result;
};

// =====================================================
// VALIDATION UTILITIES
// =====================================================

/**
 * Check if object is empty
 */
export const isEmpty = (obj: Record<string, any>): boolean => {
  return Object.keys(obj).length === 0;
};

/**
 * Check if value is valid (not null, undefined, or empty string)
 */
export const isValid = (value: any): boolean => {
  return value !== null && value !== undefined && value !== '';
};

/**
 * Debounce function calls
 */
export const debounce = <T extends (...args: any[]) => any>(
  func: T,
  wait: number
): ((...args: Parameters<T>) => void) => {
  let timeout: NodeJS.Timeout;

  return function executedFunction(...args: Parameters<T>) {
    const later = () => {
      clearTimeout(timeout);
      func(...args);
    };

    clearTimeout(timeout);
    timeout = setTimeout(later, wait);
  };
};
